# Generated by Django 5.2.4 on 2026-04-05 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('encrypted_content', models.BinaryField(blank=True, null=True)),
                ('enc_iv', models.BinaryField(blank=True, null=True)),
                ('enc_salt', models.BinaryField(blank=True, null=True)),
                ('enc_iterations', models.IntegerField(default=100000)),
                ('ver_iv', models.BinaryField(blank=True, null=True)),
                ('ver_salt', models.BinaryField(blank=True, null=True)),
                ('ver_ciphertext', models.BinaryField(blank=True, null=True)),
                ('ver_iterations', models.IntegerField(default=100000)),
                ('date_modified', models.DateTimeField()),
                ('pinned', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[('note', 'Note'), ('folder', 'Folder')], default='note', max_length=10)),
                ('parent_folder_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('visible_title', models.CharField(blank=True, max_length=500, null=True)),
                ('preview_content', models.TextField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('caret_position', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
                'indexes': [models.Index(fields=['user', 'item_type'], name='peridot_not_user_id_418773_idx'), models.Index(fields=['user', 'parent_folder_id'], name='peridot_not_user_id_e5fe39_idx')],
            },
        ),
    ]
