# Generated by Django 5.2 on 2025-05-06 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_bytes", models.BigIntegerField(default=104857600)),
                ("used_bytes", models.BigIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("content", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("locked", models.BooleanField(default=False)),
                ("encrypted", models.BooleanField(default=False)),
                (
                    "folder_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("pinned", models.BooleanField(default=False)),
                (
                    "visible_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("id", "user")},
            },
        ),
    ]
