# Generated by Django 5.2 on 2025-05-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peridot_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="iv",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="key_params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
