# Generated by Django 5.2 on 2025-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peridot_backend", "0002_note_iv_note_key_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="parent_folder_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="type",
            field=models.CharField(default="note", max_length=50),
        ),
    ]
